supportedfiles = r"*.xls  *.xlsx  *.xlsb  *.xlsm  *.ods  *.odt  *.odf  *.csv"
supportedcp = [
    "cp1250",
    "cp1251",
    "cp1252",
    "cp1253",
    "cp1254",
    "cp737",
    "cp850",
    "cp852",
    "cp857",
    "cp866",
    "cp869",
    "utf8",
]
badchars = " ?,:.!@#$%^&*()-;\n\t/\+'`˝\"Ï»¿"
charstorepl = {
    "Ą": "A",
    "ą": "a",
    "Ć": "C",
    "ć": "c",
    "Ę": "E",
    "ę": "e",
    "Ł": "L",
    "ł": "l",
    "Ó": "O",
    "ó": "o",
    "Ś": "S",
    "ś": "s",
    "Ż": "Z",
    "ż": "z",
    "Ź": "Z",
    "ź": "z",
    "ß": "ss",
}
